apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  labels:
    app: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      serviceAccountName: velocity-account
      containers:
      - name: manager
        image: eclipse-temurin:21-jdk
        command: ["java", "-jar", "/mnt/local/system/manager/bmc-manager.jar"]
        volumeMounts:
          - name: local-volume
            mountPath: /mnt/local/system/manager
      volumes:
      - name: local-volume
        hostPath:
          path: /mnt/local/system/manager
          type: Directory
