apiVersion: v1
kind: ServiceAccount
metadata:
  name: velocity-account
  namespace: minecraft

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velocity-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: velocity-account
    namespace: minecraft

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-sa
  namespace: minecraft

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubectl-role
  namespace: minecraft
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list", "get", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "expose"]
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create", "get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-role-binding
  namespace: minecraft
subjects:
  - kind: ServiceAccount
    name: kubectl-sa
    namespace: minecraft
roleRef:
  kind: Role
  name: kubectl-role
  apiGroup: rbac.authorization.k8s.io
