apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    cadvisor: "true"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        cadvisor: "true"
        kyriji.dev/enable-server-discovery: "true"
        kyriji.dev/enable-panel-discovery: "true"
        kyriji.dev/deployment-type: "process"

        kyriji.dev/initial-server: "false"
        kyriji.dev/require-startup-confirmation: "false"
        kyriji.dev/queue-strategy: "FILL"

        kyriji.dev/scale-strategy: "THRESHOLD"
        kyriji.dev/max-players: "0"
        kyriji.dev/min-instances: "1"
        kyriji.dev/max-instances: "1"
        kyriji.dev/scale-up-threshold: "0"
        kyriji.dev/scale-down-threshold: "0"
        kyriji.dev/scale-up-cooldown: "0"
        kyriji.dev/scale-down-cooldown: "0"
        kyriji.dev/scale-up-limit: "1"
        kyriji.dev/scale-down-limit: "1"
    spec:
      containers:
      - name: process
        image: {{ .Values.process.image }}
        volumeMounts:
          - name: local-volume
            mountPath: {{ .Values.volume.mountPath | default "/minecraft" }}
        env:
        {{- range .Values.process.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
      volumes:
      - name: local-volume
        persistentVolumeClaim:
          claimName: bmc-process-{{ .Values.name }}
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bmc-process-{{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    kyriji.dev/deployment-type: "process"
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: {{ .Values.global.storage.storageClass | default "longhorn" }}
  resources:
    requests:
      storage: {{ .Values.global.storage.volumeSize.process | default "2Gi" }}