environments:
  default:
    values:
      - charts/bmc-chart/values.yaml
---
repositories:
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: jetstack
    url: https://charts.jetstack.io
  - name: traefik
    url: https://traefik.github.io/charts
---
releases:
  # Traefik - only installed when ingress.installTraefik is true
  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik
    version: 28.3.0
    installed: {{ .Environment.Values.global.ingress.installTraefik | default false }}
  # MetalLB - only installed when loadBalancer.provider is "metallb"
  - name: metallb
    namespace: metallb-system
    createNamespace: true
    chart: metallb/metallb
    version: 0.14.9
    # Conditional installation based on loadBalancer provider
    installed: {{ eq .Environment.Values.global.loadBalancer.provider "metallb" }}
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - delete
          - crd
          - bfdprofiles.metallb.io,bgpadvertisements.metallb.io,bgppeers.metallb.io,ipaddresspools.metallb.io,l2advertisements.metallb.io
          - --ignore-not-found=true

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.12.0
    set:
      - name: installCRDs
        value: true
    wait: true

  - name: big-minecraft
    namespace: default
    chart: ./charts/bmc-chart
    needs:
      {{- if eq .Environment.Values.global.loadBalancer.provider "metallb" }}
      - metallb-system/metallb
      {{- end }}
      - cert-manager/cert-manager