environments:
  default:
    values:
      - local/global-config.yaml
---
repositories:
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
---
releases:
  - name: metallb
    namespace: metallb-system
    createNamespace: true
    chart: metallb/metallb
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - delete
          - crd
          - bfdprofiles.metallb.io,bgpadvertisements.metallb.io,bgppeers.metallb.io,ipaddresspools.metallb.io,l2advertisements.metallb.io
          - --ignore-not-found=true

  - name: nginx-ingress
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    needs:
      - metallb-system/metallb
    values:
      - controller:
          service:
            type: LoadBalancer
            annotations:
              metallb.universe.tf/allow-shared-ip: "shared-ip-key"
              metallb.universe.tf/loadBalancerIPs: {{ .Environment.Values.loadBalancerIP | quote }}

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.12.0
    needs:
      - ingress-nginx/nginx-ingress
    set:
      - name: installCRDs
        value: true
    wait: true

  - name: big-minecraft
    namespace: default
    chart: ./charts/bmc-chart
    needs:
      - metallb-system/metallb
      - ingress-nginx/nginx-ingress
      - cert-manager/cert-manager
    values:
      - global:
          panelDomain: {{ .Environment.Values.panelDomain }}
          k8sDashboardDomain: {{ .Environment.Values.k8sDashboardDomain }}
          loadBalancerIP: {{ .Environment.Values.loadBalancerIP }}
          inviteCode: {{ .Environment.Values.inviteCode }}
          mariaDBPassword: {{ .Environment.Values.mariaDBPassword }}
          mongoDBPassword: {{ .Environment.Values.mongoDBPassword }}
          clusterConfigPath: {{ .Environment.Values.clusterConfigPath }}
          bmcPath: {{ .Environment.Values.bmcPath }}