site_name: Big Minecraft
site_description: Kubernetes orchestrator for Minecraft server networks
site_url: https://big-minecraft.github.io/big-minecraft/
repo_url: https://github.com/big-minecraft/big-minecraft
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - navigation.footer
    - content.action.edit
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Prerequisites: prerequisites.md
  - Install:
      - Environment: environment.md
      - Cluster:
          - Bare metal: baremetal-install.md
          - Amazon EKS: eks-install.md
          - Google GKE: gke-install.md
          - Azure AKS: aks-install.md
      - BMC: bmc-install.md
  - Architecture:
      - Scaling: scaling-architecture.md

validation:
  nav:
    omitted_files: warn
    not_found: warn
  links:
    not_found: warn
    anchors: warn

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables

  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
