apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.sftp.podName }}
  labels:
    app: sftp-server
spec:
  securityContext:
    fsGroup: 1001
  restartPolicy: Never
  containers:
    - name: sftp
      image: atmoz/sftp:latest
      env:
        - name: SFTP_USERS
          value: "{{ .Values.sftp.username }}:{{ .Values.sftp.password }}:1001:1001:{{ .Values.sftp.rootPath }}"
      ports:
        - containerPort: {{ .Values.sftp.port }}
      volumeMounts:
        - name: pvc-data
          mountPath: /home/{{ .Values.sftp.username }}/{{ .Values.sftp.rootPath }}
  volumes:
    - name: pvc-data
      persistentVolumeClaim:
        claimName: {{ .Values.sftp.pvcName }}
---
apiVersion: v1
kind: Service
metadata:
  name: sftp-server
spec:
  type: NodePort
  selector:
    app: sftp-server
  ports:
    - port: 22
      targetPort: 22
      nodePort: {{ .Values.sftp.nodePort }}

