apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.sftp.podName }}
  labels:
    app: {{ .Values.sftp.podName }}
spec:
  restartPolicy: Never
  containers:
    - name: sftp
      image: emberstack/sftp:latest
      ports:
        - containerPort: 22
      volumeMounts:
        - name: pvc-data
          mountPath: /home/{{ .Values.sftp.username }}/data
        - name: sftp-config
          mountPath: /app/config/sftp.json
          subPath: sftp.json
  volumes:
    - name: pvc-data
      persistentVolumeClaim:
        claimName: {{ .Values.sftp.pvcName }}
    - name: sftp-config
      configMap:
        name: {{ .Values.sftp.podName }}-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.sftp.podName }}-config
data:
  sftp.json: |
    {
      "Global": {
        "Chroot": {
          "Directory": "%h",
          "StartPath": "data"
        }
      },
      "Users": [
        {
          "Username": "{{ .Values.sftp.username }}",
          "Password": "{{ .Values.sftp.password }}",
          "UID": 1001,
          "GID": 1001,
          "Directories": [
            "data"
          ]
        }
      ]
    }
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sftp.podName }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.sftp.podName }}
  ports:
    - port: 22
      targetPort: 22
      nodePort: {{ .Values.sftp.nodePort }}