apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-sftp-server
  labels:
    app: nfs-sftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-sftp
  template:
    metadata:
      labels:
        app: nfs-sftp
    spec:
      # Updated nodeSelector to match K3s control plane label
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      initContainers:
      - name: init-sftp-setup
        image: alpine
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Setting up SFTP directory..."
            mkdir -p /home/user/nfsshare;
            chown 1001:1001 /home/user/nfsshare;
            chmod 755 /home/user/nfsshare;
            echo "SFTP directory setup complete."
        volumeMounts:
          - name: nfs-volume
            mountPath: /home/user/nfsshare
      containers:
      - name: nfs-server
        image: itsthenetwork/nfs-server-alpine
        securityContext:
          privileged: true
        ports:
          - containerPort: 2049
        volumeMounts:
          - name: nfs-volume
            mountPath: /nfsshare
        env:
          - name: SHARED_DIRECTORY
            value: "/nfsshare"
          - name: NFS_VERSION
            value: "4"
      - name: sftp-server
        image: atmoz/sftp
        ports:
          - containerPort: 22
        env:
          - name: SFTP_USERS
            value: "user:password:1001:1001"
        volumeMounts:
          - name: nfs-volume
            mountPath: /home/user/nfsshare
      - name: file-monitor
        image: alpine
        command: ["/bin/sh", "-c"]
        args:
          - |
            apk add --no-cache inotify-tools redis
            SFTP_DIR="/home/user/nfsshare"
            REDIS_HOST="redis-service"
            REDIS_PORT=6379
            echo "Monitoring directory: $SFTP_DIR"
            echo "Connecting to Redis at $REDIS_HOST:$REDIS_PORT"
            inotifywait -m -r -e create -e modify -e delete --format '%w%f' "$SFTP_DIR" | while read FILE
            do
              echo "Event detected for file: $FILE"
              if [[ ! -e "$FILE" ]]; then
                  MESSAGE="File deleted: $FILE"
                  echo "$MESSAGE"
              else
                  MESSAGE="File changed: $FILE"
                  echo "$MESSAGE"
              fi
              echo "Publishing message to Redis: $MESSAGE"
              redis-cli -h $REDIS_HOST -p $REDIS_PORT PUBLISH file_changes "$MESSAGE" || echo "Failed to publish message to Redis"
            done
        volumeMounts:
          - name: nfs-volume
            mountPath: /home/user/nfsshare
      volumes:
      - name: nfs-volume
        hostPath:
          path: /mnt/nfsshare
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-sftp-service
spec:
  selector:
    app: nfs-sftp
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
      nodePort: 30000
    - name: sftp
      port: 22
      targetPort: 22
      nodePort: 30022
  type: NodePort