apiVersion: apps/v1
kind: Deployment
metadata:
  name: panel
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panel
  template:
    metadata:
      labels:
        app: panel
    spec:
      serviceAccountName: kubectl-sa
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: bmc-panel-storage
        - name: kube-config
          emptyDir: {}
      securityContext:
        fsGroup: 1000
      containers:
        - name: panel
          image: kyrokrypt/bmc-panel:latest
          imagePullPolicy: Always
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bmc-secrets
                  key: panelSecret
            - name: PANEL_SECRET
              valueFrom:
                secretKeyRef:
                  name: bmc-secrets
                  key: panelSecret
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bmc-secrets
                  key: panelSecret
            {{- $secret := lookup "v1" "Secret" .Release.Namespace "bmc-secrets" }}
            {{- $globalWithSecrets := deepCopy .Values.global }}
            {{- if $secret }}
            {{- $_ := set $globalWithSecrets.mariaDB "initPassword" (index $secret.data "mariadb-root-password" | b64dec) }}
            {{- $_ := set $globalWithSecrets.mongoDB "initPassword" (index $secret.data "mongodb-root-password" | b64dec) }}
            {{- $_ := set $globalWithSecrets.panel "panelSecret" (index $secret.data "panelSecret" | b64dec) }}
            {{- $_ := set $globalWithSecrets.panel "initialInviteCode" (index $secret.data "initialInviteCode" | b64dec) }}
            {{- $_ := set $globalWithSecrets.sftp "password" (index $secret.data "sftp-password" | b64dec) }}
            {{- end }}
            - name: GLOBAL_VALUES_JSON
              value: {{ $globalWithSecrets | toJson | quote }}
          volumeMounts:
            - name: storage
              mountPath: /storage
              readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: panel-service
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api$1
spec:
  selector:
    app: panel
  ports:
    - name: app
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: bmc-panel-storage
spec:
 accessModes: ["ReadWriteMany"]
 storageClassName: {{ .Values.global.storage.storageClass }}
 resources:
   requests:
     storage: {{ .Values.global.storage.volumeSize.manifests }}
---
