apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    cadvisor: "true"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  volumeClaimTemplates:
     - metadata:
          name: server-data
          labels:
            app: {{ .Values.name }}
            kyriji.dev/deployment-type: "persistent"          
       spec:
         accessModes: ["ReadWriteMany"]
         storageClassName: {{ .Values.global.storage.storageClass | default "longhorn" }}
         resources:
           requests:
             storage: {{ .Values.global.storage.volumeSize.persistent | default "10Gi" }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        cadvisor: "true"
        kyriji.dev/enable-server-discovery: "true"
        kyriji.dev/enable-panel-discovery: "true"
        kyriji.dev/deployment-type: "persistent"

        kyriji.dev/initial-server: "{{ .Values.queuing.initialServer }}"
        kyriji.dev/require-startup-confirmation: "{{ .Values.queuing.requireStartupConfirmation }}"
        kyriji.dev/queue-strategy: "FILL"

        kyriji.dev/scale-strategy: "THRESHOLD"
        kyriji.dev/max-players: "{{ .Values.scaling.maxPlayers }}"
        kyriji.dev/min-instances: "1"
        kyriji.dev/max-instances: "1"
        kyriji.dev/scale-up-threshold: "0"
        kyriji.dev/scale-down-threshold: "0"
        kyriji.dev/scale-up-cooldown: "0"
        kyriji.dev/scale-down-cooldown: "0"
        kyriji.dev/scale-up-limit: "1"
        kyriji.dev/scale-down-limit: "1"
    spec:
      containers:
      - name: mc
        image: {{ .Values.server.image }}
        command: ["/bin/bash", "/entrypoint/entrypoint.sh"]
        volumeMounts:
          - name: entrypoint
            smountPath: /entrypoint
          - name: server-data
            mountPath: {{ .Values.volume.mountPath }}
        ports:
        - containerPort: {{ .Values.server.port | default 25565 }}
          name: minecraft
        env:
        {{- range .Values.server.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        - name: REDIS_HOST
          value: {{ .Values.server.redis.host | quote }}
        - name: REDIS_PORT
          value: {{ .Values.server.redis.port | quote }}
        - name: DEPLOYMENT_NAME
          value: {{ .Values.name | quote }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
      volumes:
      - name: entrypoint
        configMap:
          name: {{ .Values.name }}-entrypoint
          defaultMode: 0755
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-entrypoint
data:
  entrypoint.sh: |
{{ (.Files.Get "scripts/entrypoint.sh") | indent 4 }}
