apiVersion: kyriji.dev/v1alpha1
kind: GameServer
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  deploymentType: persistent
  image: {{ .Values.server.image }}
  command:
    - /bin/bash
    - /entrypoint/entrypoint.sh
  port: {{ .Values.server.port | default 25565 }}
  env:
    {{- range .Values.server.env }}
    - name: {{ .name }}
      value: {{ .value | quote }}
    {{- end }}
    - name: REDIS_HOST
      value: {{ .Values.server.redis.host | quote }}
    - name: REDIS_PORT
      value: {{ .Values.server.redis.port | quote }}
    - name: DEPLOYMENT_NAME
      value: {{ .Values.name | quote }}
  resources:
    requests:
      memory: {{ .Values.resources.requests.memory }}
      cpu: {{ .Values.resources.requests.cpu }}
    limits:
      memory: {{ .Values.resources.limits.memory }}
      cpu: {{ .Values.resources.limits.cpu }}
  volume:
    mountPath: {{ .Values.volume.mountPath }}
    storageClass: {{ .Values.global.storage.storageClass | default "longhorn" }}
    size: {{ .Values.global.storage.volumeSize.persistent | default "10Gi" }}
  redis:
    host: {{ .Values.server.redis.host | quote }}
    port: {{ .Values.server.redis.port | quote }}
  scaling:
    maxPlayers: {{ .Values.scaling.maxPlayers }}
    minInstances: 1
    maxInstances: 1
  queuing:
    initialServer: {{ .Values.queuing.initialServer | quote }}
    requireStartupConfirmation: {{ .Values.queuing.requireStartupConfirmation }}
    queueStrategy: FILL
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bmc-persistent-{{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    kyriji.dev/deployment-type: "persistent"
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: {{ .Values.global.storage.storageClass | default "longhorn" }}
  resources:
    requests:
      storage: {{ .Values.global.storage.volumeSize.persistent | default "10Gi" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-entrypoint
data:
  entrypoint.sh: |
{{ tpl (.Files.Get "scripts/entrypoint.sh") . | indent 4 }}
