#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

OUTPUT_FILE="${1:-charts/bmc-chart/values.auto.yaml}"

echo "=========================================="
echo "Detecting Kubernetes Dependencies"
echo "=========================================="
echo ""

# Check Traefik (check both deployment and daemonset as k3s uses daemonset)
TRAEFIK_FOUND=false
if kubectl get deployment -n traefik traefik &>/dev/null; then
  TRAEFIK_FOUND=true
  echo -e "${GREEN}✓${NC} Traefik detected (deployment) in namespace 'traefik'"
elif kubectl get daemonset -n kube-system traefik &>/dev/null; then
  TRAEFIK_FOUND=true
  echo -e "${GREEN}✓${NC} Traefik detected (daemonset) in namespace 'kube-system' (k3s)"
else
  echo -e "${YELLOW}✗${NC} Traefik not found - will install"
fi

# Check MetalLB
METALLB_FOUND=false
if kubectl get deployment -n metallb-system controller &>/dev/null; then
  METALLB_FOUND=true
  echo -e "${GREEN}✓${NC} MetalLB detected in namespace 'metallb-system'"
else
  echo -e "${YELLOW}✗${NC} MetalLB not found - will install if provider=metallb"
fi

# Check cert-manager
CERT_MANAGER_FOUND=false
if kubectl get deployment -n cert-manager cert-manager &>/dev/null; then
  CERT_MANAGER_FOUND=true
  echo -e "${GREEN}✓${NC} cert-manager detected in namespace 'cert-manager'"
else
  echo -e "${YELLOW}✗${NC} cert-manager not found - will install"
fi

echo ""

# Generate auto-detected values file
cat > "$OUTPUT_FILE" <<EOF
# Auto-generated by scripts/detect-dependencies.sh
# This file is generated based on what's currently installed in the cluster
# DO NOT EDIT MANUALLY - will be overwritten on next detection

global:
  dependencies:
    # Traefik ingress controller
    installTraefik: $( [ "$TRAEFIK_FOUND" = true ] && echo "false" || echo "true" )

    # MetalLB load balancer (for on-premise clusters)
    installMetalLB: $( [ "$METALLB_FOUND" = true ] && echo "false" || echo "true" )

    # cert-manager for TLS certificates
    installCertManager: $( [ "$CERT_MANAGER_FOUND" = true ] && echo "false" || echo "true" )
EOF

echo -e "${GREEN}✓${NC} Generated: $OUTPUT_FILE"
echo ""

# Show what will be installed
WILL_INSTALL=()
[ "$TRAEFIK_FOUND" = false ] && WILL_INSTALL+=("Traefik")
[ "$METALLB_FOUND" = false ] && WILL_INSTALL+=("MetalLB")
[ "$CERT_MANAGER_FOUND" = false ] && WILL_INSTALL+=("cert-manager")

if [ ${#WILL_INSTALL[@]} -eq 0 ]; then
  echo -e "${GREEN}All dependencies already installed - no additional charts will be installed${NC}"
else
  echo -e "${YELLOW}Will install: ${WILL_INSTALL[*]}${NC}"
fi

echo ""
