apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    cadvisor: "true"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.scaling.minInstances }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        cadvisor: "true"
        kyriji.dev/enable-server-discovery: "true"
        kyriji.dev/enable-panel-discovery: "true"
        kyriji.dev/deployment-type: "scalable"

        kyriji.dev/initial-server: "{{ .Values.queuing.initialServer }}"
        kyriji.dev/queue-strategy: "{{ .Values.queuing.queueStrategy }}"
        kyriji.dev/require-startup-confirmation: "{{ .Values.queuing.requireStartupConfirmation }}"

        kyriji.dev/scale-strategy: "{{ .Values.scaling.scaleStrategy }}"
        kyriji.dev/max-players: "{{ .Values.scaling.maxPlayers }}"
        kyriji.dev/min-instances: "{{ .Values.scaling.minInstances }}"
        kyriji.dev/max-instances: "{{ .Values.scaling.maxInstances }}"
        kyriji.dev/scale-up-threshold: "{{ .Values.scaling.scaleUpThreshold }}"
        kyriji.dev/scale-down-threshold: "{{ .Values.scaling.scaleDownThreshold }}"
        kyriji.dev/scale-up-cooldown: "{{ .Values.scaling.scaleUpCooldown }}"
        kyriji.dev/scale-down-cooldown: "{{ .Values.scaling.scaleDownCooldown }}"
        kyriji.dev/scale-up-limit: "{{ .Values.scaling.scaleUpLimit }}"
        kyriji.dev/scale-down-limit: "{{ .Values.scaling.scaleDownLimit }}"
    spec:
      containers:
      - name: mc
        image: {{ .Values.server.image }}
        command: ["/bin/bash", "/entrypoint/entrypoint.sh"]
        volumeMounts:
          - name: entrypoint
            mountPath: /entrypoint
          - name: local-volume
            mountPath: {{ .Values.volume.mountPath | default "/minecraft" }}
            readOnly: false
          - name: tmp
            mountPath: /tmp
        ports:
        - containerPort: {{ .Values.server.port | default 25565 }}
          name: minecraft
        env:
        {{- range .Values.server.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        - name: REDIS_HOST
          value: {{ .Values.server.redis.host | quote }}
        - name: REDIS_PORT
          value: {{ .Values.server.redis.port | quote }}
        - name: DEPLOYMENT_NAME
          value: {{ .Values.name | quote }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}

      volumes:
        - name: entrypoint
          configMap:
            name: {{ .Values.name }}-entrypoint
            defaultMode: 0755
        - name: local-volume
          persistentVolumeClaim:
            claimName: bmc-scalable-{{ .Values.name }}
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bmc-scalable-{{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    kyriji.dev/deployment-type: "scalable"
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: {{ .Values.global.storage.storageClass | default "longhorn" }}
  resources:
    requests:
      storage: {{ .Values.global.storage.volumeSize.scalable | default "5Gi" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-entrypoint
data:
  entrypoint.sh: |
{{ tpl (.Files.Get "scripts/entrypoint.sh") . | indent 4 }}